name: Scrape PS3838 Corners

on:
  schedule:
    - cron: '0 * * * *'      # toutes les heures
  workflow_dispatch:        # permet un lancement manuel

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run scraper
        run: node index.js

      - name: Upload signals
        uses: actions/upload-artifact@v3
        with:
          name: corners-signals
          path: output.json
