# .github/workflows/scrape.yml (debug version)
name: Scrape PS3838 Corners

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run scraper
        run: node index.js

      - name: Debug: List workspace files
        run: |
          echo "\n--- Workspace Contents ---"
          ls -R .
          echo "-------------------------\n"

      - name: Upload signals
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: corners-signals
          path: output.json
